# -*- coding: utf-8 -*-
"""ML_practice_2(Linear regression)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qt6FsW7JZO6vkiGhYRi_gHVSEyfRpFOz
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

data=pd.read_csv("/content/car_price_prediction_with_missing.csv")

data.drop("Car ID",inplace=True,axis=1)

from sklearn import preprocessing
enc=preprocessing.OneHotEncoder()
cat=['Brand','Fuel Type','Transmission','Condition','Model']
enc.fit(data[cat])
enc.categories_

one_hot=enc.transform(data[cat]).toarray()
one_hot

import pandas as pd

cat=['Brand','Fuel Type','Transmission','Condition','Model']


new_col_names = enc.get_feature_names_out(cat)


encoded_df = pd.DataFrame(one_hot, columns=new_col_names, index=data.index)

# 4. Join them to your original data
data_final = pd.concat([data, encoded_df], axis=1)

# 5. Remove the old text columns
data_final.drop(columns=cat, inplace=True)

print(f"Total columns now: {data_final.shape[1]}")
print(data_final.head())

# Identify numerical columns
numerical_cols = data_final.select_dtypes(include=['number']).columns

# Fill missing values with mean for numerical columns
data_final[numerical_cols] = data_final[numerical_cols].fillna(data_final[numerical_cols].mean())

nan_cols = [col for col in data_final.columns if 'nan' in col.lower()]


data_final.drop(columns=nan_cols, inplace=True, errors='ignore')

data_final.head()

x=data_final.drop(['Price'],axis=1)
y=np.log1p(data_final['Price'])

from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x=sc.fit_transform(x)

from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=42)

from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(xtrain,ytrain)

ypred=model.predict(xtest)
ypred

from sklearn.metrics import root_mean_squared_error
rmse=root_mean_squared_error(ytest,ypred)

rmse

import seaborn as sns
sns.boxplot(ytest-ypred)
plt.title("outliers")
plt.show()

